batch_size: 64
num_devices: 1
num_workers: 4
acc_grd_step: 8
momentum_base: 0.9
momentum_max: 1.0
momentum_increase: true
dataset: wm811k
data_folder: '/kaggle/working/data/wm811k/labeled'
eval_metric:
  - nmi
  - acc
  - ari
whole_dataset: true
encoder_name: resnet34
epochs: 300
feat_dim: 256
hidden_size: 4096
img_size: 64
lambda_predictor_lr: 1
learning_rate: 0.03
learning_eta_min: 0.
reassign: 1
use_gaussian_blur: true
byol_transform: true

save_freq: 10
save_checkpoints: true
shuffling_bn: true
symmetric: true
temperature: 0.5
warmup_epochs: 50
weight_decay: 0.0001

model_name: propos
cluster_loss_weight: 0.03
latent_std: 0.005

wandb: false
project_name: 'clustering'
entity: '1741709996-eed'
